package com.vote.model;
// Generated 2016-7-12 13:35:20 by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * VCondidate generated by hbm2java
 */
public class VCondidate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int id;
	private String conname;
	private Integer gender;
	private String phone;
	private String position;
	private String deptname;
	private Date createdate;
	private Date updatedate;

	public VCondidate() {
	}

	public VCondidate(int id) {
		this.id = id;
	}

	public VCondidate(int id, String conname, Integer gender, String phone, String position, String deptname,
			Date createdate, Date updatedate) {
		this.id = id;
		this.conname = conname;
		this.gender = gender;
		this.phone = phone;
		this.position = position;
		this.deptname = deptname;
		this.createdate = createdate;
		this.updatedate = updatedate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getConname() {
		return this.conname;
	}

	public void setConname(String conname) {
		this.conname = conname;
	}

	public Integer getGender() {
		return this.gender;
	}

	public void setGender(Integer gender) {
		this.gender = gender;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getDeptname() {
		return this.deptname;
	}

	public void setDeptname(String deptname) {
		this.deptname = deptname;
	}

	public Date getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	public Date getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Date updatedate) {
		this.updatedate = updatedate;
	}

}
